### ISSUE TITLE
P1: Centers > Education Center Terms > Al Rawabi School > Modify ALP Education Stage Section

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#212]
Creating a Section in a Term causes the app to crash.
http://eaci.joe.me:8088/TermManagement/StageSections/Create
Also, there should not be a Section dropdown list in the Create Section form.

**Comment by RaymondYounan** [comment]
You can now create an Education Center Term with no errors.
@DrJoeHage: Why do we need to remove the section dropdown, where will we get the section from?

**Comment by DrJoeHage** [comment]
@RaymondYounan How can you be displaying a Section dropdown in the form called Create Section? I don't understand. We should discuss on the phone.

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
- In LEMIS mode, verified that the user is able to create, edit and delete a Section in an Education Center Term.
- In EACI mode, the user is not able to create a Section in an Education Center Term since the user is not able to select a value for the "Term" field.
- Verified for both LEMIS and EACI modes that the "Section" drop down list is no longer available.

**Comment by RaymondYounan** [comment]
@tannourynadine Are you sure there are terms already created for EACI?

**Comment by tannourynadine** [comment]
Yes. @RaymondYounan

**Comment by RaymondYounan** [comment]
@tannourynadine Done. Please try this on newly created Session Terms.

**Comment by tannourynadine** [comment]
Verified for both EACI and LEMIS modes that the user is able to create, edit and delete a Section in an Education Center Term.
