### ISSUE TITLE
P2: Student Gender Preference Form is allowing duplicate entries

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#261]
Each entry must be unique. In other words, a male student may have only one Male preference and one Mixed preference. One of each and not more.
![student-gender-preference](https://cloud.githubusercontent.com/assets/9402931/6149309/a0a17680-b210-11e4-9fec-a0b0a68fa506.jpg)

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
**Verified the following:**
- A male student, is only able to create a male or a mixed gender preference.
- A female student, is only able to create a female or a mixed gender preference.

**Encountered the following issues:**
**Issue 1:**
- Pick up a male or a female student and then click on the "Manage Literacy Student Gender Preference".
- Create one entry for each gender. (e.g.: one male entry and one mixed entry)
- Pick a gender preference and delete it. (e.g.: delete the male entry)
- Now, create a new entry having the same value as the one deleted. (e.g.: recreate the male entry)
- **Actual Result:** an error message is generated notifying the user that the entry already exists. (Please note that the value was created and deleted before trying to create it again.)

**Issue 2:**
- Not able to test the "Student Gender Preference" form in EACI mode, since it's not displayed in the Student management drop down menu.

**Comment by RaymondYounan** [comment]
Issue 1: Fixed
Issue 2: Fixed

**Comment by tannourynadine** [comment]
Verified for both the EACI and LEMIS modes the following:
- A male student, is only able to create one entry for male or a mixed gender preference.
- A female student, is only able to create one entry for female or a mixed gender preference.
- The user is able to recreate a deleted entry with no issues.
