### ISSUE TITLE
P0: Need to add a User Privileges option

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#336]
This option will help restrict what the user sees data-wise and will include 8 Privilege settings:
Country
Governorate
District
General Directorate
Directorate
Education Center
School
Facility
I implemented the table UserPreference and it is in the script dated 201511270545 or later.

**Comment by RaymondYounan** [comment]
User Privilege functionality added in the user management page.
@DrJoeHage Please fix the type of UserID to nvarchar(128) instead of int
@Rfarran You can start implementing this in registration, The table containing the schools/Facilities/EducationCenters is UserFacilitySchoolBuildingPrivilege (Please pay attention to the ObjectStatus)

**Comment by DrJoeHage** [comment]
@RaymondYounan In the UserPreference table, we have PersonID as int. You want me to replace PersonID by UserID nvarchar(128)? Please confirm.

**Comment by RaymondYounan** [comment]
@DrJoeHage yes, since we're giving the privilege to a user not to a person

**Comment by DrJoeHage** [comment]
@RaymondYounan I was getting an application crash. So I had to rename the UserID field in UserPreference to ID. However, I can only Delete an existing User Preference. I cannot modify it. I cannot Create a New user privilege because the "User Privilege Level" dropdown is blank.

**Comment by RaymondYounan** [comment]
Done
