### ISSUE TITLE
P1: Student form is allowing to select a Female only School for a Male student

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#370]
Add a new Literacy Student with Gender=Male
The Education Center dropdown is showing ALL Literacy Centers instead of just the Male ones.

This is causing to have Male students show up in the Grade Sections UI.

**Comment by Rfarran** [comment]
Fixed

**Comment by DrJoeHage** [comment]
@RaymondYounan Issue still there as of Dec.13 build.

**Comment by Rfarran** [comment]
@DrJoeHage The issue is fixed. when you select the gender, the drop down list only shows the centers related to this gender. Please let me know what the issue is other than this

**Comment by DrJoeHage** [comment]
There are two problems:
1. When I Modify an existing Student, and his/her gender is already defined, if I go to the Education Center dropdown, it will list ALL of them. It does not filter them. It only triggers the filtering on the selection of the Gender. Not if it is already set.
2. You need to observe not only the gender but also the property set for "Accepts Mixed Classrooms?" as Yes or No. If this is set to No, then the Mixed type educ centers should not be listed in the the Education Center dropdown.

**Comment by Rfarran** [comment]
Point one resolved and checked In
Point two:
@DrJoeHage 
To resolve this, we need an additional field that tells me if the mapping record needs approval (I cannot hardcode that "3" is the Mixed mapping for example).
To do this, @RaymondYounan  needs to add the field. I have done all the necessary code changes to the file "StudentsController.cs" in the area "StudentsManagement".
So after you add the field and generate the model, you just need to modify the filter to be:
m => m.PersonEducCenterGenderMappingObjectStatusID == 1 && m.GenderID == id && (bAcceptsMix || m.NeedsMixApproval == false)

I have added the below ToDo commented to the controller so that you can directly copy/paste :)

//Todo:
            //[Rami Farran]: this should also filter if the user accepts mix or not
            //Need to add field NeedsMixApproval of type boolean to the table PersonEducCenterGenderMapping
            //to do this, we need to add: && (bAcceptsMix || m.NeedsMixApproval == false) to the filter above
            //the filter will become:
            //.Where(m => m.PersonEducCenterGenderMappingObjectStatusID == 1 && m.GenderID == id && (bAcceptsMix || m.NeedsMixApproval == false)).ToList<...

**Comment by RaymondYounan** [comment]
Done.

@DrJoeHage  Can you add the field NeedsMixApproval of type bit to the table PersonEducCenterGenderMapping and fill the values.

This field will be true where the EducCenterGender is Mix (Records 2 and 5)

**Comment by DrJoeHage** [comment]
@RaymondYounan and @Rfarran Added the field as requested. No null allowed.

**Comment by DrJoeHage** [comment]
Verified and Documentation updated.
