### ISSUE TITLE
P2: Student Management > Student Exam Records in a Section form is missing

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#54]
Form needed to enter exam records of multiple students in a given Grade Section to avoid having to enter them one by one.

**Comment by RaymondYounan** [comment]
Done

**Comment by DrJoeHage** [comment]
Where is this form? How can I access it?

**Comment by RaymondYounan** [comment]
Application Administration > Grade Section > each Section you can click on ManageLiteracyStudentsExamRecords

**Comment by tannourynadine** [comment]
Verified that the "Manage Students exam Records" form is available at the Application Administration > Grade Section.
Encountered the following issue, the user is not able to enter data of a Student in an Exam.
- Navigate to Application Administration > Grade Section
- Select an Education Center Term and then click on the "Manage Literacy Student Exam Records" button.
- Choose an Exam and then Click on the "Manage Literacy Student Exam Records" button.
- Notice that the user is taken to the "Manage Literacy Students Exam Records" page and he is not able to enter data for a Student since there is no create button.

![exam](https://cloud.githubusercontent.com/assets/3637417/6147391/b1685dd2-b1ff-11e4-9eb1-86acc94f845c.png)

**Comment by RaymondYounan** [comment]
@tannourynadine, please make sure that there are student registered in the exam, then you will be able to give them grades.

**Comment by tannourynadine** [comment]
- In LEMIS mode navigate to Application Administration > Grade Section > then click on the "Manage Literacy Student Exam Records" button for Section 1.
- Select "Mid-Term Exam" and then click on "Literacy Student Exam Records" button.
- Enter Data for the Student Narimane and then click on the "Save" button.
- An error message is generated and the user is not able to save the entered information.

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
- Verified that the "Manage Students exam Records" form is available at the Application Administration > Grade Section.
- Verified that for a register student in a exam, the user is able to enter data a for a specific exam and the information will be save correctly.
- Could not verify this issue for EACI mode due to issue #278.
